apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jhub-ingressroute
  namespace: jhub
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jhub. domain.com`)
      kind: Rule
      services:
        - name: proxy-public
          kind: Service
          port: 80

