apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jhub-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jhub-kn. domain.com`)
      kind: Rule
      services:
        - name: proxy-public
          kind: Service
          port: 80

