apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jhub-kn-1cl-cc-tls
spec:
  secretName: jhub-kn-1cl-cc-tls
  dnsNames:
    - "jhub-kn. domain.com"
    - "*.jhub-kn. domain.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
